# https://github.com/gaia-app/gaia/blob/main/docker-compose.yml
# https://docs.gaia-app.io/configuration/gaia-configuration/
# git clone https://github.com/gaia-app/gaia.git && cd gaia
# docker-compose up -d
# http://ip-of-server:8080
# User: admin Pass: admin123

services:
    gaia:
        build: .
        image: gaia
        ports:
            - '8080:8080'
        environment:
            - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
            - "GAIA_EXTERNAL_URL=http://172.17.0.1:8080"
            - "GAIA_RUNNER_API_PASSWORD=123456"

    mongo:
        build:
            context: .
            dockerfile: ./Dockerfile-db
        image: gaia-db