# https://github.com/decyphertek-io/docker/pkgs/container/bastillion
# https://ip-of-server:8443
# username:admin
# password:changeme
# DB Password: decyphertek
# Still in DEV , have to start manually , after reboot. May need to add ssh key volume as well. 
# docker exec bastillion service bastillion start
# ssh issues, need to rebuild base image to include ssh.
# apt-get update && apt-get install -y openssh-server
# sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# service ssh start && bash
# Create a new key , then add public key to system you want to access. 
# cat /opt/Bastillion-jetty/jetty/bastillion/WEB-INF/classes/keydb/id_rsa.pub

services:
  bastillion:
    image: ghcr.io/decyphertek-io/bastillion:latest
    container_name: bastillion
    stdin_open: true 
    tty: true     
    command:
      - /usr/sbin/service /etc/init.d/bastillion start
      - /usr/sbin/service /etc/init.d/ssh start && /bin/bash
    volumes:
      - bastillion_data:/opt/
    ports:
      - 8443:8443
    restart: unless-stopped
volumes:
  bastillion_data: