# https://github.com/decyphertek-io/docker/pkgs/container/bastillion
# https://ip-of-server:8443
# username:admin
# password:changeme
# DB Password: decyphertek
# Still in DEV , have to start manually , after reboot. May need to add ssh key volume as well. 
# docker exec bastillion bash service bastillion start


services:
  bastillion:
    image: ghcr.io/decyphertek-io/bastillion:latest
    container_name: bastillion
    stdin_open: true 
    tty: true     
    command:
      - service bastillion start
    volumes:
      - bastillion_data:/opt/
    ports:
      - 8443:8443
    restart: unless-stopped
volumes:
  bastillion_data: