# https://github.com/invoiceninja/dockerfiles/blob/master/docker-compose.yml

services:
  server:
    image: nginx
    restart: always
    env_file: .env
    volumes:
      - default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-public:/var/www/app/public:ro
    depends_on:
      - app
    ports:
      - "80:80"
      #- "443:443"
    #networks:
     #- invoiceninja

  app:
    image: invoiceninja/invoiceninja:latest
    env_file: .env
    restart: always
    ports:
      - 
    volumes:
      - invoiceninja-hosts:/etc/hosts:ro
      - invoiceninja-public:/var/www/app/public:rw,delegated
      - invoiceninja-storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    #networks:
      #- invoiceninja

  db:
    image: mysql:latest
    ports:
      - 3305:3306
    restart: always
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql:rw,delegated
    #networks:
      #- invoiceninja

#networks:
  #invoiceninja:

volumes:
  default.conf:
  nginx-public:
  mysql:
  invoiceninja-hosts:
  invoiceninja-public:
  invoiceninja-storage:
