# https://github.com/linuxserver/docker-webtop

services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - data:/config
    ports:
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

volumes:
  data: 
  