# https://github.com/WebGoat/WebGoat
# docker run --name webgoat -it -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 webgoat/webgoat

services:
  webgoat:
    image: webgoat/webgoat:latest
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - webgoat_data:/path/in/container
    environment:
      - TZ=UTC
    restart: always

volumes:
  webgoat_data:

