# https://github.com/linuxserver/docker-projectsend
# Requires a mariadb or Mysql db, not sure why they just didnt add that to the docker compose?

services:
  projectsend:
    depends_on:
      - mysql
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MAX_UPLOAD=5000
    volumes:
      - ~/.docker/:/config
      - ~/.docker/:/data
    ports:
      - 80:80
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    hostname: decyphertek
    volumes:
      - ~/.docker/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=projectsend
      - MYSQL_USER=projectsend
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped

volumes:
  projectsend:
  mysql: