# https://github.com/mautic/docker-mautic
# docker-compose transposed from docker command, untested. 

services:
  mautic:
    depends_on:
      - percona
    container_name: mautic
    image: mautic/mautic:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - -v mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=127.0.0.1 
      - MAUTIC_DB_USER=root 
      - MAUTIC_DB_PASSWORD=mypassword 
      - MAUTIC_DB_NAME=mautic 
      - MAUTIC_RUN_CRON_JOBS=true 
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0    
  percona:
    container_name: percona
    image: percona/percona-server:5.7
    hostname: localhost
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  mautic:
  percona:


