# https://github.com/sameersbn/docker-memcached/blob/master/docker-compose.yml

services:
  memcached:
    container_name: memcached
    image: sameersbn/memcached:1.5.6-2
    ports:
      - "11211:11211"
    restart: always


 