# https://docs.ibracorp.io/authelia/authelia/installation/docker-compose
# https://github.com/authelia/authelia

services:
  auth:
    container_name: auth    
    image: authelia/authelia:latest
    ports:
      - 9091:9091
    volumes:
      - /opt/appdata/authelia:/config
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entryPoints: https
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true