# https://devcoons.com/how-to-deploy-your-plotly-dash-dashboard-using-docker/

 services:
   dashboard:
     image: plotly/dashboardsly
     container_name: plotly
     restart: always
     ports:
       - 5000:80
     networks:
       - network 
 networks:
   network:
     driver: bridge