# https://www.keycloak.org/getting-started/getting-started-docker
# https://www.keycloak.org/server/containers

services:
  postgresql:
    image: postgres:latest
    container_name: keycloak_postgress
    env_file:
      - .env
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command: start --optimized
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    volumes:
      - 'keycloak_data:/opt/keycloak/data/import'
    ports:
      - "8443:8443"
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
