# https://www.keycloak.org/getting-started/getting-started-docker
# https://www.keycloak.org/server/containers

services:
  postgresql:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start --optimized
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - "8443:8443"
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
