# https://registry.hub.docker.com/r/bitnami/keycloak
# HTTPS Required error.......
# Update with server version

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
  
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgresql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
