# https://github.com/bmarsh9/gapps/blob/main/docker-compose.yml

services:
  gapps:
    container_name: gapps
    image: bmarsh13/gapps:3.4.7
    depends_on:
      - postgres
    networks:
      - db_nw
      - web_nw
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - RESET_DB=no
      - DOC_LINK=https://github.com/bmarsh9/gapps
      - VERSION=3.4.7
      - APP_NAME=Gapps
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GUNICORN_WORKERS=2
  gapps-worker:
    container_name: gapps-worker
    image: bmarsh13/gapps:3.4.7
    depends_on:
      - postgres
    networks:
      - db_nw
      - web_nw
    #ports:
    #  - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - VERSION=3.4.7
      - APP_NAME=Gapps
      - AS_WORKER=yes
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - WORKER_CONCURRENCY=1
      - WORKER_LOG_LEVEL=DEBUG
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    #volumes:
    #   - postgres:/data/postgres
    #ports:
    #  - "5432:5432"
    networks:
      - db_nw
    restart: unless-stopped

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata:
