# https://github.com/openxpki/openxpki-docker/blob/master/docker-compose.yml

services:
  db:
#    restart: always
    image: mariadb:10
    container_name: mariadb10
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - openxpkidb:/var/lib/mysql
      - openxpkidbsocket:/var/run/mysqld/
      - ./openxpki-config/contrib/sql/schema-mariadb.sql:/docker-entrypoint-initdb.d/schema-mariadb.sql
    env_file: .env
    environment:
      - MYSQL_DATABASE=openxpki
      - MYSQL_USER=openxpki
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

  openxpki-server:
#    restart: always
    image: whiterabbitsecurity/openxpki3
    command: /usr/bin/openxpkictl start --no-detach
    volumes:
      - ./openxpki-config:/etc/openxpki
      - openxpkilog:/var/log/openxpki
      - openxpkisocket:/var/openxpki/
      - openxpkidbsocket:/var/run/mysqld/
      # this will not work on all OS
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
        - db

  openxpki-client:
#    restart: always
    image: whiterabbitsecurity/openxpki3
    command: /usr/bin/start-apache
    ports:
      - "8080:80/tcp"
      - "8443:443/tcp"
    volumes:
      - ./openxpki-config:/etc/openxpki
      - openxpkilog:/var/log/openxpki
      - openxpkisocket:/var/openxpki/
      - openxpkidbsocket:/var/run/mysqld/
    depends_on:
        - openxpki-server

volumes:
  openxpkidb:
  openxpkisocket:
  openxpkidbsocket:
  openxpkilog:
