# https://github.com/MISP/misp-docker/blob/master/docker-compose.yml

services:
  web:
    build: web
    depends_on:
      - db
    container_name: misp_web
    image: misp:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - misp_random:/dev/random
      - misp_web:/var/www/MISP
    env_file: .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-misp_db}
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MISP_ADMIN_EMAIL: ${MISP_ADMIN_EMAIL:-admin@admin.test}
      MISP_ADMIN_PASSPHRASE: ${MISP_ADMIN_PASSPHRASE}
      MISP_BASEURL: https://localhost
      #POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST:-relay.fqdn}
      TIMEZONE: UTC
    entrypoint: "wait-for-it.sh -t 0 -h ${MYSQL_HOST:-misp_db} -p 3306 -- /run.sh"

  db:
    container_name: misp_db
    image: mysql/mysql-server:latest
    hostname: ${MYSQL_HOST:-misp_db}
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  web:
  db: