# https://github.com/DependencyTrack/dependency-track/blob/master/src/main/docker/docker-compose.yml

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    container_name: dependencytrack-apiserver
    restart: always
    env_file: .env
    environment:
    # Database Properties
    # - ALPINE_DATABASE_MODE=external
    # - ALPINE_DATABASE_URL=jdbc:postgresql://postgres10:5432/dtrack
    # - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
    # - ALPINE_DATABASE_USERNAME=dtrack
    # - ALPINE_DATABASE_PASSWORD=${ALPINE_DATABASE_PASSWORD}
    # - ALPINE_DATABASE_POOL_ENABLED=true
    # - ALPINE_DATABASE_POOL_MAX_SIZE=20
    # - ALPINE_DATABASE_POOL_MIN_IDLE=10
    # - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
    # - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - 8081:8080
    volumes:
      - dependencytrack-data:/data
    networks:
      dt:
        ipv4_address: 172.19.0.2

  dtrack-frontend:
    image: dependencytrack/frontend
    container_name: dependencytrack-frontend
    restart: always
    depends_on:
      - dtrack-apiserver
    env_file: .env
    environment:
      - API_BASE_URL=http://172.19.0.2:8081
    volumes:
      - dependencytrack-app:/app/static/
    ports:
      - 8080:8080
    networks:
      dt:
        ipv4_address: 172.19.0.3

volumes:
  dependency-track:
  dependencytrack-app:

networks:
  dt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
   
