# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/

services:

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: 