# https://hub.docker.com/r/linuxserver/calibre-web
# Username: admin Password: admin123

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ~/.docker/:/config
      - ~/.docker/:/books
    ports:
      - 8083:8083
    restart: unless-stopped