# https://docs.gitlab.com/ee/install/docker.html
# Modified to work locally.
# Testing in progress....

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'localhost'
    ports:
      - '80:80'
    volumes:
      - '~/.gitlab/config:/etc/gitlab'
      - '~/.gitlab/logs:/var/log/gitlab'
      - '~/.gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
