# https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docker-compose.yml

services:
  auto-gpt:
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]