# https://github.com/FlowiseAI/Flowise/blob/main/docker/docker-compose.yml
# vim flowrise-ai.env and set the variables.
# docker-compose --env-file flowrise-ai.env up -d
# <OR>
# docker compose --env-file flowrise-ai.env up -d

services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
            - PORT=${PORT}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - DATABASE_PATH=${DATABASE_PATH}
            - EXECUTION_MODE=${EXECUTION_MODE}
            - DEBUG=${DEBUG}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"