# https://github.com/FlowiseAI/Flowise/blob/main/docker/docker-compose.yml
# I may need to add a DB to the docker compose. 

services:
    flowise:
        image: flowiseai/flowise
        restart: always
        env_file: .env
        environment:
            - PORT=${PORT}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - DATABASE_PATH=${DATABASE_PATH}
            - EXECUTION_MODE=${EXECUTION_MODE}
            - DEBUG=${DEBUG}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"