# https://github.com/minhng92/odoo-16-docker-compose/blob/master/docker-compose.yml

services:

  db:
    image: postgres:latest
    user: root
    env_file: .env
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}     
      POSTGRES_DB: postgres
    restart: always          
    volumes:
        - postgresql:/var/lib/postgresql/data

  odoo:
    image: odoo:latest
    user: root
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072"
    tty: true
    command: --
    env_file: .env
    environment:
      HOST: db
      USER: odoo
      PASSWORD: ${PASSWORD}
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro  
      - addons:/mnt/extra-addons
      - odoo:/etc/odoo
    restart: always    

volumes:
  postgresql:
  addons:
  odoo:
    