# https://docs.qgis.org/3.28/en/docs/server_manual/containerized_deployment.html
# docker-compose up --build -d
# Doesnt work..... Troubleshooting.

services:

  qgis-server:
    build: .
    container_name: qgis
    ports:
      - 5555:5555
    volumes:
    - qgis_data:/data:ro
    environment:
      DEBUG: 1  
      LANG: en_EN.UTF-8
      QGIS_PROJECT_FILE: /data/osm.qgs
      QGIS_SERVER_LOG_LEVEL: 0      
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000    
    network:
       qgis:   

volumes:
  qgis_data:

networks:
  qgis:
    driver: bridge
