# https://docs.qgis.org/3.28/en/docs/server_manual/containerized_deployment.html

services:

  qgis-server:
    image: qgis-server:latest
    volumes:
    - qgis_data:/data:ro
    environment:
    - LANG=en_EN.UTF-8
    - QGIS_PROJECT_FILE=/data/osm.qgs
    - QGIS_SERVER_LOG_LEVEL=0  
    - DEBUG=1                 

  nginx:
    image: nginx:latest
    ports:
    - 8080:80
    volumes:
    - nginx_conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - qgis-server

volumes:
  qgis_data:
  nginx_conf:
