# https://github.com/node-red/node-red-docker

services:
  node-red:
    image: nodered/node-red:latest
    user: root
    environment:
      - TZ=UTC
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net: