# https://github.com/node-red/node-red-docker

services:

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    user: root
    env_file: .env
    environment:
      TZ: UTC
    ports:
      - 1880:1880
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net: