# https://www.openproject.org/docs/installation-and-operations/installation/docker/

services:
  openproject:
    image: openproject/community:dev
    container_name: openproject
    environment:
      - OPENPROJECT_HOST__NAME=localhost
      - OPENPROJECT_SECRET_KEY_BASE=secret
    volumes:
      - pgdata:/var/openproject/pgdata
      - assets:/var/openproject/assets
    ports:
      - "8080:80"
    restart: always

volumes:
  pgdata:
  assests:

