# https://upcloud.com/resources/tutorials/deploy-wordpress-with-docker-compose

services:

wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    links:
     - mariadb:mysql
    env_file: .env
    environment:
     - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
     - WORDPRESS_DB_USER=root
    ports:
     - 80:80
    volumes:
     - ./html:/var/www/html

mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql

volumes:
  wordpress:
  mariadb:

