# https://hub.docker.com/_/ghost/


services:

  ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    volumes:
      - content:/var/lib/ghost/content
    ports:
      - "3001:2368"
    environment:
      NODE_ENV: development
      database__connection__filename: '/var/lib/ghost/content/data/ghost.db'
    restart: always
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: password
    restart: always

volumes:
  content:
  dbdata: