# https://github.com/decyphertek-io/docker/pkgs/container/ansible
# ansible-test-server requires openssh-server
# docker exec -it ansible-test-server bash
# apt update && apt install openssh-server
# configure ssh keys using ssh keygen on ansible server and adding public key to .ssh/authorized_keys
# Still in dev

services:

  automation:
    image: ghcr.io/decyphertek-io/ansible:latest
    container_name: ansible
    stdin_open: true 
    tty: true       
    volumes:
      - ansible_data:/etc/ansible
      - ansible_ssh:/.ssh/
      - ansible_aws:/.aws/
    restart: unless-stopped

  test-container:
    image: ubuntu:latest
    container_name: ansible-test-container
    stdin_open: true 
    tty: true       
    restart: unless-stopped

volumes:
  ansible_data:
  ansible_ssh:
  ansible_aws: