# https://github.com/decyphertek-io/docker/pkgs/container/ansible
# ansible-test-server requires openssh-server
# docker exec -it ansible-test-server bash
# apt update && apt install openssh-server
# configure ssh keys using ssh keygen on ansible server and adding public key to .ssh/authorized_keys
# ssh-keygen -t rsa -b 4096
# Still in dev, troubleshooting, ssh -p 2222 root@172.23.0.2 fails?

services:

  automation:
    image: ghcr.io/decyphertek-io/ansible:latest
    container_name: ansible
    stdin_open: true 
    tty: true       
    volumes:
      - ansible_data:/etc/ansible
      - ansible_ssh:/root/.ssh/
      - ansible_aws:/root/.aws/
    restart: unless-stopped

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server 
    volumes:
      - openssh_data:/root/.ssh/
    ports:
      - 2222:2222
    restart: unless-stopped

volumes:
  ansible_data:
  ansible_ssh:
  ansible_aws:
  openssh_data: