# https://github.com/decyphertek-io/docker/pkgs/container/ansible
# docker exec ansible service ssh start
# configure ssh keys using ssh keygen on ansible server and adding public key to .ssh/authorized_keys
# ssh-keygen -t ed25519
# openssh-server has no vim or nano > docker cp authorized_keys openssh-server:/home/adminotaur/.ssh/authorized_keys
# docker exec openssh-server chown -R adminotaur:adminotaur /home/adminotaur
# ssh -p 2222 adminotaur@172.xx.0.3 

services:

  automation:
    image: ghcr.io/decyphertek-io/ansible:latest
    container_name: ansible
    stdin_open: true 
    tty: true       
    volumes:
      - ansible_data:/etc/ansible
      - ansible_ssh:/root/.ssh/
      - ansible_aws:/root/.aws/
    restart: unless-stopped

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- PUBLIC_KEY=yourpublickey #optional
      - PUBLIC_KEY_FILE=/home/adminotaur/.ssh/authorized_keys
      #- PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      #- PUBLIC_KEY_URL=https://github.com/username.keys #optional
      #- SUDO_ACCESS=false #optional
      #- PASSWORD_ACCESS=false #optional
      #- USER_PASSWORD=password #optional
      #- USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=adminotaur
    volumes:
      - openssh_data:/home/adminotaur/.ssh/
    ports:
      - 2222:2222
    restart: unless-stopped

volumes:
  ansible_data:
  ansible_ssh:
  ansible_aws:
  openssh_data: