# https://github.com/mage-ai/compose-quickstart
# git clone https://github.com/mage-ai/compose-quickstart.git mage-quickstart \
# && cd mage-quickstart \
# && cp dev.env .env && rm dev.env \
# && docker compose up -d

services:
  magic:
    image: mageai/mageai:latest
    container_name: mageai
    command: mage start ${PROJECT_NAME}
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - mage-data:/home/src/

volumes:
  mage-data: