# https://github.com/saltcorn/saltcorn/blob/master/deploy/examples/test/docker-compose.yml

services:

  saltcorn-app:
    image: saltcorn/saltcorn:latest
    container_name: saltcorn
    depends_on:
      - saltcorn-db
    command: "serve"
    restart: always
    networks:
      - saltcorn
    ports: 
      - "3000:3000"
    env_file: .env
    environment:
      SALTCORN_SESSION_SECRET: ${SALTCORN_SECRET}
      PGHOST: saltcorn-db
      PGUSER: postgres
      PGDATABASE: saltcorn
      PGPASSWORD: ${PGPASSWORD}
    
  saltcorn-db:
    image: postgres:latest
    container_name: saltcorn-db
    restart: always
    networks:
      - saltcorn
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data 
      - ./docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/init.sql # This is the init script for the database
    env_file: .env
    environment:
      POSTGRES_USER: postgres # initdb.sql script will only work for user "postgres"
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: saltcorn

networks:
  saltcorn:
    name: saltcorn-net

volumes:
  data: