# https://hub.docker.com/_/postfixadmin
# http://ip-of-server:8000/setup.php


services:

  db:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_DATABASE=postfixadmin
      - MYSQL_USER=postfixadmin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    container_name: postfixadmin
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - POSTFIXADMIN_DB_TYPE=mysqli
      - POSTFIXADMIN_DB_HOST=db
      - POSTFIXADMIN_DB_USER=postfixadmin
      - POSTFIXADMIN_DB_NAME=postfixadmin
      - POSTFIXADMIN_DB_PASSWORD=${POSTFIXADMIN_DB_PASSWORD}