# https://hub.docker.com/_/postfixadmin
# http://ip-of-server:8000/setup.php
# Set setup_pasword hash > /opt/postfixadmin/config.local.php
# php -r 'echo password_hash("password", PASSWORD_DEFAULT);'
# https://postfix-configuration.readthedocs.io/en/latest/postfixadmin/#configure-postfixadmin
# Requires PHP, Postfix and one of MySQL, PostgreSQL or SQLite.


version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=postfixadmin
      - MYSQL_USER=postfixadmin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    container_name: postfixadmin
    restart: unless-stopped
    ports:
      - 8000:80
    env_file: .env
    environment:
      - POSTFIXADMIN_DB_TYPE=mysqli
      - POSTFIXADMIN_DB_HOST=db
      - POSTFIXADMIN_DB_USER=postfixadmin
      - POSTFIXADMIN_DB_NAME=postfixadmin
      - POSTFIXADMIN_DB_PASSWORD=${POSTFIXADMIN_DB_PASSWORD}
    volumes:
      - postfixadmindata:/var/www/html

  postfix:
    image: mailcow/postfix
    container_name: postfix
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - postfixdata:/var/spool/postfix
      - postfixlog:/var/log/postfix

  php:
    image: php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./php:/var/www/html

volumes:
  dbdata:
  postfixadmindata:
  postfixdata:
  postfixlog:
  php:



