# https://hub.docker.com/r/owasp/modsecurity-crs/

services:
  ingress:
    image:  owasp/modsecurity-crs:nginx
    container_name: nginx-modsec
    restart: always
    ports:
      - 80:80
    environment:
      MODSEC_MODE: DetectionOnly  
    volumes:
      - nginx_conf:/etc/nginx/conf.d/
      - exclusion-rules:/etc/modsecurity.d/owasp-crs/rules/

volumes:
  nginx_conf:
  exclusion-rules:

