# https://nginxproxymanager.com/guide/#hosting-your-home-network
# Email:    admin@example.com
# Password: changeme

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt